"""add_ai_generated_column

Revision ID: 48996f9ebaf2
Revises: 39219c95b53f
Create Date: 2026-05-11 22:33:51.221633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48996f9ebaf2'
down_revision: Union[str, Sequence[str], None] = '39219c95b53f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('ai_generated', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'ai_generated')
    # ### end Alembic commands ###
