"""add_public_key_to_users

Revision ID: 836bafbc1a38
Revises: dc8c55f35856
Create Date: 2026-05-03 14:55:04.393235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '836bafbc1a38'
down_revision: Union[str, Sequence[str], None] = 'dc8c55f35856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_key')
    # ### end Alembic commands ###
