"""add_moderation_note

Revision ID: 9c5794bbaa1b
Revises: 836bafbc1a38
Create Date: 2026-05-06 16:44:10.775061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c5794bbaa1b'
down_revision: Union[str, Sequence[str], None] = '836bafbc1a38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('moderation_note', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'moderation_note')
    # ### end Alembic commands ###
